package com.june.domain.mapper;

import com.june.domain.model.OdaaSequence;

import java.util.List;

public interface OdaaSequenceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table odaa_sequence
     *
     * @mbg.generated Thu Nov 09 22:08:17 CST 2023
     */
    int deleteByPrimaryKey(String bizKey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table odaa_sequence
     *
     * @mbg.generated Thu Nov 09 22:08:17 CST 2023
     */
    int insert(OdaaSequence row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table odaa_sequence
     *
     * @mbg.generated Thu Nov 09 22:08:17 CST 2023
     */
    OdaaSequence selectByPrimaryKey(String bizKey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table odaa_sequence
     *
     * @mbg.generated Thu Nov 09 22:08:17 CST 2023
     */
    List<OdaaSequence> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table odaa_sequence
     *
     * @mbg.generated Thu Nov 09 22:08:17 CST 2023
     */
    int updateByPrimaryKey(OdaaSequence row);
}